# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ListenList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SQLite.swift'
  # Pods for ListenList

  target 'ListenListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListenListUITests' do
    # Pods for testing
  end

end
